### ISSUE TITLE
BUG context/user/cluster names aren't always the same

### ISSUE THREAD

**Issue by mattclegg** [mnubo/kubernetes-py#23]
This bug occurs if the context/user/cluster name don't match. Consider the following;

```
contexts:
    cluster: prod
    user: matt
  name: prod_matt
```
